#!/bin/sh

CONFIGFILE=/etc/emoncms-debconf.conf

# Source debconf library.
. /usr/share/debconf/confmodule

# Fetching configuration from debconf
db_get emoncms/mysql_user
DB_USER=$RET
db_get emoncms/mysql_password
DB_PASSWORD=$RET
db_get emoncms/mysql_host
DB_HOST=$RET
db_get emoncms/mysql_db
DATABASE=$RET

db_get emoncms/smtp_host
SMTP_HOST=$RET
db_get emoncms/smtp_user
SMTP_USER=$RET
db_get emoncms/smtp_password
SMTP_PASSWORD=$RET
db_get emoncms/smtp_email_addr
SMTP_EMAIL_ADDR=$RET
db_get emoncms/smtp_email_name
SMTP_EMAIL_NAME=$RET

db_get emoncms/enable_password_reset
ENABLE_PASSWORD_RESET=$RET

# Print some confirmation output to screen
echo "Replacing existing emoncms config as follows:"
echo " - MySQL configuration   : $DB_USER connecting to $DATABASE db on $DB_HOST"
echo " - SMTP configuration    : $SMTP_USER connecting to $SMTP_HOST to send as $SMTP_EMAIL_NAME ($SMTP_EMAIL_ADDR)"
echo " - Allow password resets : $ENABLE_PWD_RESET"

# Write out debian config file.
echo "# Config file for emoncms" > $CONFIGFILE
echo "DB_USER=\"$DB_USER\"" >> $CONFIGFILE
echo "DB_PASSWORD=\"$DB_PASSWORD\"" >> $CONFIGFILE
echo "DB_HOST=\"$DB_HOST\"" >> $CONFIGFILE
echo "DATABASE=\"$DATABASE\"" >> $CONFIGFILE

echo "SMTP_HOST=\"$SMTP_HOST\"" >> $CONFIGFILE
echo "SMTP_USER=\"$SMTP_USER\"" >> $CONFIGFILE
echo "SMTP_PASSWORD=\"$SMTP_PASSWORD\"" >> $CONFIGFILE
echo "SMTP_EMAIL_ADDR=\"$SMTP_EMAIL_ADDR\"" >> $CONFIGFILE
echo "SMTP_EMAIL_NAME=\"$SMTP_EMAIL_NAME\"" >> $CONFIGFILE
  
echo "ENABLE_PASSWORD_RESET=\"$ENABLE_PASSWORD_RESET\"" >> $CONFIGFILE

# To support backwards compatibility with people cloning git into their docroot, we need to rename the settings file here.
mv /usr/share/emoncms/www/default.settings.php /usr/share/emoncms/www/settings.php

# Update the settings.php file with the configuration values:
sed -i "s/_DEBCONF_DB_USER_/$DB_USER/g" /usr/share/emoncms/www/settings.php
sed -i "s/_DEBCONF_DB_PASSWORD_/$DB_PASSWORD/g" /usr/share/emoncms/www/settings.php
sed -i "s/_DEBCONF_DATABASE_/$DATABASE/g" /usr/share/emoncms/www/settings.php
sed -i "s/_DEBCONF_DB_HOST_/$DB_HOST/g" /usr/share/emoncms/www/settings.php
sed -i "s/_DEBCONF_SMTP_HOST_/$SMTP_HOST/g" /usr/share/emoncms/www/settings.php
sed -i "s/_DEBCONF_SMTP_USER_/$SMTP_USER/g" /usr/share/emoncms/www/settings.php
sed -i "s/_DEBCONF_SMTP_PASSWORD_/$SMTP_PASSWORD/g" /usr/share/emoncms/www/settings.php
sed -i "s/_DEBCONF_SMTP_EMAIL_ADDR_/$SMTP_EMAIL_ADDR/g" /usr/share/emoncms/www/settings.php
sed -i "s/_DEBCONF_SMTP_EMAIL_NAME_/$SMTP_EMAIL_NAME/g" /usr/share/emoncms/www/settings.php
sed -i "s/_DEBCONF_ENABLE_PASSWORD_RESET_/$ENABLE_PASSWORD_RESET/g" /usr/share/emoncms/www/settings.php

if [ -f /var/lib/timestore/adminkey.txt ]
then
  read -r TS_ADMIN_KEY < /var/lib/timestore/adminkey.txt
  perl -pi -e "s{_DEBCONF_TS_ADMINKEY_}{$TS_ADMIN_KEY}" /usr/share/emoncms/www/settings.php
  echo " - Copied timestore key from /var/lib/timestore/adminkey.txt into emoncms config"
fi

# Create the required feed directories and set ownership
echo "Verifying feed directories exist and have the correct ownership..."
echo " - /var/lib/phpfiwa"
mkdir -p /var/lib/phpfiwa
chown www-data:root /var/lib/phpfiwa/

echo " - /var/lib/phpfina"
mkdir -p /var/lib/phpfina
chown www-data:root /var/lib/phpfina/

echo " - /var/lib/phptimeseries"
mkdir -p /var/lib/phptimeseries
chown www-data:root /var/lib/phptimeseries/

echo " - /var/lib/timestore"
mkdir -p /var/lib/timestore
chown www-data:root /var/lib/timestore/

# Create the MySQL db (if it doesn't already exist).
echo "Attempting to create '$DATABASE' mysql database (with the '$DB_USER' user)..."
mysql -u$DB_USER -p$DB_PASSWORD -e "CREATE DATABASE IF NOT EXISTS $DATABASE;" || { echo ' - Failed (check username and password are correct, using dpkg-reconfigure. Check grants allow table creation, etc...)' ; exit 1; }

# Didn't exit 1? Then DB creation worked OK.
echo " - '$DATABASE' either exists already or was created successfully."

echo "To update emoncms configuration, run 'dpkg-reconfigure emoncms'"

exit 0
